### PR TITLE
Added plugins from Tal, Chair, ChowDSP, Cardinal

### PR DESCRIPTION
**Pull request by wSzki**
Hello 

I've successfully added VST3 from [CHAIR audio](https://www.chair.audio/product/excite_snare_drum/) and [Tal](https://tal-software.com/) 

I'm a git & nix noob so please let me know if it works 
Tested on Nixos 23.05 with Renoise

### CODE REVIEW

**Comment by wSzki** [comment]
Added [chowDSP](https://chowdsp.com/products.html) <strike>and [CardinalSynth from Distrho](https://github.com/DISTRHO/Cardinal) plugins since i can't figure out how to use the existing ones in  nixos' [environment.systemPackages](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=chow)
Any tips?</strike>

Edit : just needed a reboot, but still keeping chowDSP as not all plugins are available on the official nix channel 

The plugins seems to be wiped by `nix-store --gc`, any idea on how to prevent that?

Planning on adding 

- [ ] [LSP plugins](https://lsp-plug.in/?page=manuals&section=impulse_reverb_stereo)
- [ ] [Pianoteq](https://www.modartt.com/) Having issues with dynamic download link
- [ ] [BomShanka](https://bomshankamachin.es/)
- [ ] [OB-XD](https://www.discodsp.com/obxd/) having issues with install script and `$(xdg-user-dir DOCUMENTS)`
- [ ] <strike>[Dexed](https://asb2m10.github.io/dexed/)</strike> Official package works
- [ ] [Renoise](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=renoise) since the package from the official channel is outdated 
- [ ] <strike>CardinalFX (VCV Rack VST Fork)</strike> Official package works
- [ ] <strike>CardinalMain</strike> Official package works

**Comment by evenbrenden** [comment]
First of all, this is an impressive amount of work, well done!

The reason I keep this repo around is because it's tricky to properly pack u-he plugin binaries for NixOS. Since many of the plugins you listed are already added to [Nixpkgs](https://github.com/NixOS/nixpkgs) (the source repo of what you would typically put in `environment.systemPackages`), someone should have gotten them working for NixOS, and you should try to get them working as is on your system too. I suggest asking for help on the [NixOS Discourse](discourse.nixos.org). In my experience, people are very helpful there, and if you send me a link to your question (just post it here on this PR), I might be able to help out too.

As for plugins that do not exist in Nixpkgs, I suggest trying to add them yourself by making a [PR](https://github.com/NixOS/nixpkgs/pulls). You already did most of the work! Having them in Nixpkgs will make them much more readibly available for other people than having them here.

Lastly, I want to keep this repo exclusive to _u-he_ plugins, so I'm going to close this PR. If you still have similar problems with some of the plugins from this PR after trying the things mentioned above, I suggest starting separate projects for those (in the same vein as this repo).

> The plugins seems to be wiped by nix-store --gc, any idea on how to prevent that?

[This article](https://ianthehenry.com/posts/how-to-learn-nix/saving-your-shell/) might answer that. Note garbage collection will not be problem if the plugins are packaged properly, for example by adding them to Nixpkgs.

> Renoise since the package from the official channel is outdated

Overriding versions is the way to go, for instance see [Overriding | nixpkgs](https://ryantm.github.io/nixpkgs/using/overrides/).

**Comment by wSzki** [comment]
Thanks for the valuable pointers and taking the time to reply!

Gotcha, I eventually had a hunch that this repo might be u-he exclusive when i realized most plugin installs were quite straightforward :)

I'm still confused regarding the linking of the plugins `.so` files from the `store` to the `~/.vst` and `~/.vst3` folders during the `nix-build` which doesn't seem to allow it.
I can't figure out what search engine keywords to use to learn about this. Any tips for this as well?

Cardinal ([nixpkgs source](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/audio/cardinal/default.nix#L82)) for example is automatically detected as a VST plugin but not listed int the `~/.vst` folder, so I'm wondering how that works as i don't see anything in the `.nix` file related to that

Anyway your repo was a huge help to get me started on Nixos packaging, so thanks again for sharing :+1:

**Comment by evenbrenden** [comment]
> I'm still confused regarding the linking of the plugins .so files from the store to the ~/.vst and ~/.vst3 folders during the nix-build which doesn't seem to allow it.

Simply put: Packages can only be installed to `/nix/store`. When you see an install step like `cp -r plugin.so $out/lib/vst`, it means that `plugin.so` ends up in `/nix/store/.../lib/vst`. Further, things that end up in `/nix/store/.../lib` are linked to `~/.nix-profile/lib`. From there on, it is common to set environment variables like `VST_PATH=~/.nix-profile/lib` so that apps knows where to look for plugins. As an example, see [my dotfiles](https://github.com/evenbrenden/dotfiles/blob/7f5f3a54bbc0194f96d440eaa1e870f909dab71b/home/studio/studio.nix#L34) where I set these using Home Manager.

**Comment by evenbrenden** [comment]
> Cardinal ([nixpkgs source](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/audio/cardinal/default.nix#L82)) for example is automatically detected as a VST plugin but not listed int the ~/.vst folder, so I'm wondering how that works as i don't see anything in the .nix file related to that

Looks like the Cardinal package does not include any plugins, just a standalone executable. If there's a plugin in there, you could try to change the derivation to include it :slightly_smiling_face:

**Pull request closed without merging**
